# Generated by Django 6.0.2 on 2026-02-17 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_order_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="store",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last update timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Creation timestamp."
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="description",
            field=models.TextField(blank=True, help_text="Optional store description."),
        ),
        migrations.AlterField(
            model_name="store",
            name="name",
            field=models.CharField(
                help_text="The store's display name.", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="owner",
            field=models.ForeignKey(
                help_text="The vendor account that owns this store.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("owner", "name")},
        ),
    ]
